AC={namespace:function(){var a=arguments,o=null,i,j,d,rt;for(i=0;i<a.length;++i){d=a[i].split(".");rt=d[0];eval("if (typeof "+rt+' == "undefined") {'+rt+" = {};} o = "+rt+";");for(j=1;j<d.length;++j){o[d[j]]=o[d[j]]||{};o=o[d[j]]}}}};AC.namespace("AC","AC.Page","AC.UI","AC.UTILS");AC.namespace("AC.UI.Tab");
AC.UI.Tab={change:function(tabNav,activeClass,tabCon){$(tabCon).each(function(){$(this).children().eq(0).show()});$(tabNav).each(function(){$(this).children().eq(0).addClass(activeClass)});$(tabNav).children().click(function(){$(this).addClass(activeClass).siblings().removeClass(activeClass);var index=$(tabNav).children().index(this);$(tabCon).children().eq(index).show().siblings().hide()})}};AC.namespace("AC.UI.Input");
AC.UI.Input={insertText:function(inputId,inputText){var inputObject=$("#"+inputId);inputObject.focus();var textObj=inputObject.get(0);if(document.all&&textObj.createTextRange){var textRange=document.selection.createRange();textRange.text=inputText}else if(textObj.setSelectionRange){var rangeStart=textObj.selectionStart;var rangeEnd=textObj.selectionEnd;var tempStr1=textObj.value.substring(0,rangeStart);var tempStr2=textObj.value.substring(rangeEnd);var len=inputText.length;textObj.value=tempStr1+
inputText+tempStr2;textObj.setSelectionRange(rangeStart+len,rangeStart+len)}else textObj.value+=inputText;inputObject.trigger("input")},moveEnd:function(inputId){var inputObject=$("#"+inputId);inputObject.focus();var inputObject=inputObject.get(0);var len=inputObject.value.length;if(document.selection){var sel=inputObject.createTextRange();sel.moveStart("character",len);sel.collapse();sel.select()}else if(typeof inputObject.selectionStart=="number"&&typeof inputObject.selectionEnd=="number")inputObject.selectionStart=
inputObject.selectionEnd=len}};AC.namespace("AC.UI.Dialog");AC.UI.Dialog={showAction:function(elementId){showDialog.show({id:elementId,bgcolor:"#000",opacity:70})},showMsg:function(msgContent,msgType){var msgCss=msgType=="1"?"succeed":msgType=="2"?"failed":"warning";showDialog.show({sMsg:msgContent,sClass:msgCss,bgcolor:"#000",sTime:3E3,opacity:70})},hide:function(){showDialog.hide()}};AC.namespace("AC.UTILS.Browser");
AC.UTILS.Browser={userAgentLower:navigator.userAgent.toLowerCase(),checkUserAgent:function(regex){return regex.test(this.userAgentLower)},isOpera:function(){return this.checkUserAgent(/opera/)},isChrome:function(){return this.checkUserAgent(/\bchrome\b/)},isSougo:function(){return this.checkUserAgent(/se .+ metasr/)},isSafari:function(){return!this.isChrome()&&this.checkUserAgent(/safari/)},isIE:function(){return!this.isOpera()&&this.checkUserAgent(/msie/)},isIE6:function(){return this.isIE()&&this.checkUserAgent(/msie 6/)}};
AC.namespace("AC.UTILS.Include");
AC.UTILS.Include={FilePath:"",Path:function(path){var path=path||"";if(typeof path!=="string"){throw new Error("path --\> string");return}else if(this.FilePath!=="")return;this.FilePath+=path},Loader:function(urls,callback){var self=this,path=self.FilePath,script=$("head").find("script"),successCallback=arguments[1],failCallback=arguments[2];var loaderMethod={loaderReady:function(urls){var dtd=$.Deferred(),node=document.createElement("script"),isExist=false,resolved;node.type="text/javascript";resolved=
function(){dtd.resolve()};if(!urls.match(/.js/i))return;if(script[0])script.each(function(){if($(this).attr("src")===urls){isExist=true;resolved()}});if(!isExist){$(node).load(resolved).bind("readystatechange",function(){if(node.readyState=="loaded"||node.readyState=="complete"){node.onreadystatechange=null;resolved()}});document.getElementsByTagName("head")[0].appendChild(node);node.src=urls}return dtd.promise()},loaderAction:function(urls){var that=this,ret=[],newUrl=[];if(typeof urls==="string")ret.push(that.loaderReady(path+
urls));else{var i=0,l=urls.length;for(;i<l;i++){newUrl.push(path+urls[i]);ret.push(that.loaderReady(newUrl[i]))}}return $.when.apply($,ret).done(function(){successCallback&&successCallback()}).fail(function(){failCallback&&failCallback()})}};return loaderMethod.loaderAction(urls)}};AC.namespace("AC.Page");
AC.Page={loadImage:function(container,force){if(undefined==container||container=="")$("img.lazy").lazyload({threshold:100,failurelimit:10});else if(undefined!=force&&true==force)$(container).find("img.lazy").each(function(){var src=$(this).attr("src");var original=$(this).attr("data-original");if(src!=""&&original!=""&&original!=src)$(this).attr("src",original)});else $(container).find("img.lazy").lazyload({threshold:100,failurelimit:10})},registerLoadImage:function(btn,container,eventName){$(btn).bind(eventName,
"",function(){AC.Page.loadImage(container,true)})},processUrl:function(url){if(url=="http://ac.qq.com"||url=="http://ac.qq.com/")url="http://ac.qq.com/index?auth=1";else if(url.indexOf("?")!=-1)url=url+(url.indexOf("auth=1")!=-1?"":"&auth=1");else url=url+(url.indexOf("auth=1")!=-1?"":"?auth=1");return url},showLogin:function(url,target){if(undefined==url||url=="")url=location.href;else{var httpPos=url.indexOf("http");if(httpPos<0)url=location.protocol+"//"+location.hostname+url+location.search}url=
AC.Page.processUrl(url);if(undefined==target||target=="")target="top";else target="self";$.blockUI({message:$("#loginframe"),css:{top:"30%",left:"55%",border:"none"}});document.domain="qq.com";$("#login_ifr").attr("src","http://ui.ptlogin2.qq.com/cgi-bin/login?style=0&appid=637009801&target=self&daid=43&s_url="+encodeURIComponent("http://ac.qq.com/loginSuccess.html?url="+encodeURIComponent(url)));$(".blockPage").css({"height":"382px","left":"50%","top":"50%","width":"400px","margin":"-191px 0 0 -200px"})},
hideLogin:function(){$.unblockUI();$("#login_ifr").attr("src","javascript://")},reload:function(url){$.unblockUI();if(url)window.location.href=url;else window.location.reload()},coreBind:function(){AC.UI.Tab.change("#mod-log-handle","active","#mod-log-main");AC.UI.Tab.change("#mod-log-his-handle","active","#mod-log-his-panel");AC.Page.Core.bindEvent();AC.Page.Core.setPanelPagination("",3)},LoadUserBaseInfo:function(hdFlag){if(!AC.Page.cookie("skey")){AC.Page.Core.avatar="http://ac.gtimg.com/media/images/top_face_no_bg.jpg";
AC.Page.Core.hasLogin="0";AC.Page.Core.nick="";AC.Page.Core.uin=0;AC.Page.Core.uinCrypt=0;AC.Page.Core.token="";AC.Page.cleanUserCookie();AC.Page.showUserImage();return}$.ajax({type:"GET",url:"/Ajax/getUserBaseInfo",data:"hd="+hdFlag,async:false,cache:false,timeout:2E3,success:function(data){var data=$.parseJSON(data);if(data.status==2){AC.Page.Core.hasLogin="1";AC.Page.Core.avatar=data.result.avatar;AC.Page.Core.nick=data.result.shortNick;AC.Page.Core.token=data.result.token;AC.Page.Core.uin=data.result.uin;
if(hdFlag){$("#mod-top-user").find("a").attr("title",data.result.shortNick);$("#mod-top-user").find("img").attr("src",data.result.avatar);$("#mod-top-log").show();$("#faceimg").attr("src",data.result.avatar).attr("title",data.result.shortNick)}}else if(data.status==-99)if(hdFlag){$("#faceimg").attr("src","http://ac.gtimg.com/media/images/top_face_no_bg.jpg");$(".mod-top-user-msg").live("click",function(){AC.Page.showLogin(location.pathname)});$("#sc").bind("click",function(){Event.addCollect()}).addClass("comm ht sc").removeClass("sced").css("cursor",
"pointer")}}})},LoadUserInfo:function(){if(AC.Page.checkSkey()&&AC.Page.getUserCookie()){AC.Page.showUserImage();return}if(!AC.Page.cookie("skey")){AC.Page.Core.avatar="http://ac.gtimg.com/media/images/top_face_no_bg.jpg";AC.Page.Core.hasLogin="0";AC.Page.Core.nick="";AC.Page.Core.uin=0;AC.Page.Core.uinCrypt=0;AC.Page.Core.token="";AC.Page.cleanUserCookie();AC.Page.showUserImage();return}$.ajax({type:"get",url:"/Ajax/getUserBaseInfo",data:"",async:false,cache:false,timeout:2E3,success:function(data){var data=
$.parseJSON(data);if(data.status!=undefined&&data.status==2){data=data.result;AC.Page.Core.avatar=data.avatar;AC.Page.Core.hasLogin="1";AC.Page.Core.nick=data.shortNick;AC.Page.Core.uin=data.uin;AC.Page.Core.uinCrypt=data.uinCrypt;AC.Page.Core.token=data.token;AC.Page.setUserCookie()}else if(data.status==-97){$("#top-user-info").hide();AC.Page.logout()}else{AC.Page.Core.avatar="http://ac.gtimg.com/media/images/top_face_no_bg.jpg";AC.Page.Core.hasLogin="0";AC.Page.Core.nick="";AC.Page.Core.uin=0;AC.Page.Core.uinCrypt=
0;AC.Page.Core.token="";AC.Page.cleanUserCookie()}AC.Page.showUserImage()},error:function(XMLHttpRequest,textStatus,errorThrown){}})},showUserImage:function(){var data={};data.avatar=AC.Page.Core.avatar;data.hasLogin=AC.Page.Core.hasLogin;data.nick=AC.Page.Core.nick;data.uin=AC.Page.Core.uin;data.token=AC.Page.Core.token},logout:function(){pt_logout.logout();this.cleanCookie();AC.Page.cleanUserCookie();setTimeout(function(){location.reload()},500)},checkSkey:function(){var c=AC.Page.cookie("skey");
if(c!=null&&c!="")return true;return false},getUserCookie:function(){var c=AC.Page.cookie("pc_userinfo_cookie");if(c!=null&&c!=""){var object=JSON.parse(c);if(typeof object!="object")return false;AC.Page.Core.uin=object.uin;AC.Page.Core.uinCrypt=object.uinCrypt;AC.Page.Core.nick=object.nick;AC.Page.Core.avatar=object.avatar;AC.Page.Core.hasLogin=object.hasLogin;AC.Page.Core.token=object.token}return AC.Page.Core.uin>0},setUserCookie:function(){var object={"uin":AC.Page.Core.uin,"uinCrypt":AC.Page.Core.uinCrypt,
"nick":AC.Page.Core.nick,"avatar":AC.Page.Core.avatar,"hasLogin":AC.Page.Core.hasLogin,"token":AC.Page.Core.token};var date=new Date;date.setTime(date.getTime()+36E5);AC.Page.cookie("pc_userinfo_cookie",JSON.stringify(object),{path:"/",expires:date})},cleanUserCookie:function(){AC.Page.cookie("pc_userinfo_cookie","",{path:"/","expires":1})},cleanCookie:function(){var i={};i.domain="ac.qq.com";i.path="/";this.cookie("p_skey","",i);this.cookie("p_uin","",i)},cookie:function(name,value,options){if(typeof value!=
"undefined"){options=options||{};if(value===null){value="";options.expires=-1}var expires="";if(options.expires&&(typeof options.expires=="number"||options.expires.toUTCString)){var date;if(typeof options.expires=="number"){date=new Date;date.setTime(date.getTime()+options.expires*24*60*60*1E3)}else date=options.expires;expires="; expires="+date.toUTCString()}var path=options.path?"; path="+options.path:"";var domain=options.domain?"; domain="+options.domain:"";var secure=options.secure?"; secure":
"";document.cookie=[name,"=",encodeURIComponent(value),expires,path,domain,secure].join("")}else{var cookieValue=null;if(document.cookie&&document.cookie!=""){var cookies=document.cookie.split(";");for(var i=0;i<cookies.length;i++){var cookie=jQuery.trim(cookies[i]);if(cookie.substring(0,name.length+1)==name+"="){cookieValue=decodeURIComponent(cookie.substring(name.length+1));break}}}return cookieValue}},ajaxChangePage:function(page,url){$.ajax({type:"post",url:url,data:{"objid":$("#objid").val(),
"page":page},beforeSend:function(){$("#commentList").html('<span class="loading">\u52a0\u8f7d\u4e2d\uff0c\u8bf7\u7a0d\u540e...</span>')},error:function(XMLHttpRequest,textStatus,errorThrown){$("#commentList").html('\u52a0\u8f7d\u5931\u8d25\uff0c\u8bf7<a href="javascript:void(0);" onclick="">\u91cd\u8bd5</a>')},success:function(data){if(data.substr(0,1)+""=="1"){$("#commentList").html(data.substr(1));bind();pagination(url)}else if(data.substr(0,1)+""=="2")$("#commentList").html(data.substr(1));else{art.dialog({content:data.substr(1),
time:2E3});$("#commentList").html("")}}});return false}};function ptlogin2_onClose(){$.unblockUI()}AC.namespace("AC.Page.Core");
AC.Page.Core={nick:"",avatar:"",uin:"",init:function(){AC.Page.Core.Timetstamp=(new Date).getTime();AC.Page.loadImage();this.bindForRank();AC.Page.Core.sideTool();this.searchStyle();AC.Page.LoadUserInfo();AC.Page.coreBind();this.channel()},channel:function(){var channel=AC.Page.cookie("ac_channel");if(channel==null){var url=window.location.search;if(url!=""){var index=url.indexOf("ADTAG");if(index!=-1)AC.Page.cookie("ac_channel",$.trim(url.substring(index+14)))}}},bindForRank:function(){$(".mod_rank_wr").each(function(){$(this).find(".mod_rank_list").eq(0).css("display",
"block")});$(".mod_rank_tab li").click(function(){var css="current";if(!$(this).hasClass(css)){var tmp=this.id.split("_");if(tmp.length>0){var flag=tmp[0];var id=tmp[1];for(var i=1;i<=4;i++){$("#"+flag+"_"+i).removeClass(css);$("#d_"+flag+"_"+i).hide()}$("#d_"+flag+"_"+id).show();$(this).addClass(css)}}})},bindEvent:function(){$("#a_login").live("click",function(){AC.Page.showLogin(location.pathname)});$("#bookshelf_login").live("click",function(){AC.Page.showLogin(location.pathname)});$("#a_logout").live("click",
function(){$("#top-user-info").hide();AC.Page.logout()});$("#igonAllComic").live("click",function(){AC.Page.Core.igonAllComic()});$(".mod-top-user").hoverDelay({outDuring:200,hoverEvent:function(){$obj=$(this);var timestamp=(new Date).getTime();if(AC.Page.Core.firstLoad!=1||AC.Page.Core.Timetstamp+1E4<timestamp){AC.Page.Core.Timetstamp=timestamp;$.get("/Ajax/getUserInfo",{stamp:Math.random()},function(data){AC.Page.Core.firstLoad=1;if(data.status==2){$obj.attr("data",timestamp);data=data.result;$("#mod-dropdown-info").html(template.render("script-user-info-dropdown",
data));$("#mod-top-user").find("img").first().attr("src",data.avatar);$(".mod-user-msg-wr").attr("style","display:block");AC.Page.Core.avatar=data.avatar;AC.Page.Core.hasLogin="1";AC.Page.Core.nick=data.shortNick;AC.Page.Core.uin=data.uin;AC.Page.Core.uinCrypt=data.uinCrypt;AC.Page.Core.token=data.token;AC.Page.setUserCookie()}else if(data.status==-99){$("#mod-dropdown-info").html("");$("#mod-top-user").find("img").first().attr("src","http://ac.gtimg.com/media/images/top_face_no_bg.jpg");$(".mod-user-msg-wr").attr("style",
"display:none");AC.Page.cleanUserCookie()}else if(data.status==-97){$("#top-user-info").hide();AC.Page.logout()}},"json")}},outEvent:function(){}});$(".mod-top-log").hoverDelay({outDuring:200,hoverEvent:function(){var timestamp=(new Date).getTime();if(AC.Page.Core.Timetstamp+1E4<timestamp){AC.Page.Core.loadFavoritUpdate();AC.Page.Core.Timetstamp=timestamp}},outEvent:function(){}});$("#mod-top-log-history").die("click").live("click",function(){var timestamp=(new Date).getTime();if(AC.Page.Core.Timetstamp+
1E4<timestamp){AC.Page.Core.loadReadHistory();AC.Page.Core.Timetstamp=timestamp}});this.directH5btn()},directH5btn:function(){},igonAllComic:function(){$.post("/Ajax/ignoreUpdate",{"tokenKey":AC.Page.Core.token},function(data){if(data.status==1){$("#mod-log-fav-mh").html('<div class="mod-userlog-tips"><h3>\u60a8\u6536\u85cf\u7684\u6f2b\u753b\u6682\u65e0\u66f4\u65b0</h3><p class="ui-mb40">sorry,\u4f5c\u8005\u6b63\u5728\u52aa\u529b\u8d76\u7a3f\u4e2d\uff0c\u660e\u5929\u518d\u6765\u770b\u770b\u5427\uff01</p></div>');
$("#mod-top-log").find(".mod-user-msg-num").text("0").hide()}else if(data.status==-98||data.status==-99)AC.Page.showLogin(location.pathname)},"json")},doSearch:function(formId){var form=$("#"+formId),input=form.find(".mod-search-input"),label=form.find(".mod-search-label"),submit=form.find(".mod-search-submit"),search={init:function(){if(input.val()!=="")label.hide();else label.show()},bindEvent:function(){var self=this;input.focusin(function(){var val=$(this).val();$.trim(val)===""&&label.hide()}).focusout(function(){var val=
$(this).val();self.isNull(val)&&label.hide()||label.show()});submit.click(function(){var val=input.val();if(!self.isNull(val))return false;else location.replace("/Comic/searchList/search/"+val,false)})},isNull:function(val){return $.trim(val)!==""&&$.trim(val)!==null}};search.init();search.bindEvent()},searchStyle:function(){$("#ui-search-list li").first().addClass("active");$("#ui-search-list li").last().addClass("last");$("#ui-search-list li").mouseover(function(){$(this).addClass("active").siblings().removeClass("active")});
$("#top-search-input").live("focus",function(){if($(this).val()=="")$(this).parents(".mod-top-search").find(".ui-search-list-wrap").show()});$(document).bind("click",function(e){var target=$(e.target);if(target.closest(".mod-top-search-wr").length==0)$(".ui-search-list-wrap").hide()});$("#top-search-input").live("keyup",function(){if($(this).val()!="")$(this).parents(".mod-top-search").find(".ui-search-list-wrap").hide()});this.doSearch("top-search");$("#top-search-input").autocomplete("/Comic/search",
{delay:100,minChars:1,width:384,matchSubset:1,matchContains:1,autoFill:false,cacheLength:10,formatItem:function(item){if(item[0]=="505430")return"<a href='javascript:void(0)'>"+item[1]+"\uff08\u6d77\u8d3c\u738b\uff09"+"</a>";else if(item[0]=="501661")return"<a href='javascript:void(0)'>"+item[1]+"\uff08\u6b7b\u795e\uff09"+"</a>";else return"<a href='javascript:void(0)'>"+item[1]+"</a>"},onItemSelect:function(li){if(li.selectValue!==null&&li.selectValue.length>0){pgvSendClick({hottag:"NEW.AC_SEARCH.KEYWORD.LIANXIANG"});
location.replace("/Comic/ComicInfo/id/"+li.selectValue,false)}}})},loadReadHistory:function(){if(AC.Page.Core.hasLogin=="1")$.get("/Ajax/getReadHistory",{stamp:Math.random()},function(data){if(data.status==2){var comicHisTotal=data.comicResult.length;if(comicHisTotal>0)for(var i=0;i<comicHisTotal;i++){data.comicResult[i]["delType"]=3;data.comicResult[i]["comicName"]=decodeURIComponent(data.comicResult[i].comicName);data.comicResult[i]["shortComicName"]=decodeURIComponent(data.comicResult[i].shortComicName).substring(0,
15);data.comicResult[i]["comicLink"]="/Comic/comicInfo/id/"+data.comicResult[i].id;data.comicResult[i]["finishStateCss"]=parseInt(data.comicResult[i].finishState)===1?"ui-icon-new":"ui-icon-done";data.comicResult[i]["latedChapterName"]=data.comicResult[i].latedChapterName;data.comicResult[i]["shortLatedChapterName"]=data.comicResult[i].latedChapterName.substring(0,9);data.comicResult[i]["coverUrl"]="http://ugc.qpic.cn/manhua_cover/0/"+data.comicResult[i].coverUrl+"/100";data.comicResult[i]["link"]=
data.comicResult[i].cid!=0?"/ComicView/index/id/"+data.comicResult[i].id+"/seqno/"+data.comicResult[i].viewNo+"/ref/dbsc":"javascript:void(0)";data.comicResult[i]["nextComicLink"]="/ComicView/index/id/"+data.comicResult[i].id+"/seqno/"+data.comicResult[i].nextSeqNo+"/ref/dbsc";data.comicResult[i]["latedComicLink"]="/ComicView/index/id/"+data.comicResult[i].id+"/seqno/"+data.comicResult[i].latedSeqNo+"/ref/dbsc"}var cartoonHisTotal=data.cartoonResult.length;if(cartoonHisTotal>0)for(var i=0;i<cartoonHisTotal;i++){data.cartoonResult[i]["delType"]=
4;data.cartoonResult[i]["link"]="/Cartoon/detail/id/"+data.cartoonResult[i].id+"/sid/"+data.cartoonResult[i].viewNo+"/ref/dbyd";data.cartoonResult[i]["cartoonName"]=decodeURIComponent(data.cartoonResult[i].cartoonName);data.cartoonResult[i]["shortCartoonName"]=decodeURIComponent(data.cartoonResult[i].shortCartoonName).substring(0,10);data.cartoonResult[i]["nextCartoonLink"]="/Cartoon/detail/id/"+data.cartoonResult[i].id+"/sid/"+data.cartoonResult[i].nextEpisodeId+"/ref/dbyd";data.cartoonResult[i]["photoUrl"]=
data.cartoonResult[i].photoUrl!=null&&data.cartoonResult[i].photoUrl!=""?data.cartoonResult[i].photoUrl:""}$("#mod-log-his-mh").html(template.render("script-mod-log-his-mh",data));$("#mod-log-his-dh").html(template.render("script-mod-log-his-dh",data));AC.Page.Core.setPanelPagination("#mod-log-his-mh",3)}},"json");else{var comicStr=AC.Page.cookie("readRecord");var comicJson=eval(comicStr)||[];var comicSubJson={items:[]};for(var i=0;i<comicJson.length;i++)if(comicJson[i][0]!==null&&comicJson[i][2]!==
null){var item={"comicId":comicJson[i][0],"chapterId":comicJson[i][2]};comicSubJson.items.push(item)}if(comicSubJson.items.length>0)$.get("/Ajax/getChapterInfo",{comicInfoList:JSON.stringify(comicSubJson.items),stamp:Math.random()},function(result){var data={"comicResult":[]};if(result.status==1)for(var i=0;i<comicJson.length;i++){if(!result[comicJson[i][0]])continue;var nextComicLink="/ComicView/index/id/"+comicJson[i][0]+"/seqno/"+result[comicJson[i][0]].info.nextSeqNo+"/ref/dbsc";var latedComicLink=
"/ComicView/index/id/"+comicJson[i][0]+"/seqno/"+result[comicJson[i][0]].info.latedSeqNo+"/ref/dbsc";var finishStateCss=parseInt(result[comicJson[i][0]].finishState)===1?"ui-icon-new":"ui-icon-done";var comicName=comicJson[i][1];item={"id":comicJson[i][0],"cid":comicJson[i][2],"delType":1,"viewNo":comicJson[i][4],"latedSeqNo":result[comicJson[i][0]].info.latedSeqNo,"latedChapterId":result[comicJson[i][0]].info.latedChapterId,"comicName":comicName,"finishStateCss":finishStateCss,"latedComicLink":latedComicLink,
"nextComicLink":nextComicLink,"shortComicName":comicName.substring(0,10),"latedChapterName":result[comicJson[i][0]].info.latedChapterName,"nextChapterName":result[comicJson[i][0]].info.nextChapterName,"coverUrl":"http://ugc.qpic.cn/manhua_cover/0/"+result[comicJson[i][0]].coverUrl+"/0","link":"/ComicView/index/id/"+comicJson[i][0]+"/cid/"+comicJson[i][2]+"/ref/dbyd","comicLink":"/Comic/comicInfo/id/"+comicJson[i][0]};data.comicResult.push(item)}$("#mod-log-his-mh").html(template.render("script-mod-log-his-mh",
data));AC.Page.Core.setPanelPagination("#mod-log-his-mh",3)},"json");else{var data={"comicResult":[]};$("#mod-log-his-mh").html(template.render("script-mod-log-his-mh",data))}var data={"cartoonResult":[]};var cartoonStr=AC.Page.cookie("ac_cartoon_readhistory");var cartoonJson=eval(cartoonStr)||[];for(var i=0;i<cartoonJson.length;i++){var tmp=cartoonJson[i];if(tmp==null||tmp=="")continue;var photoUrl=tmp[4]!=null&&tmp[4]!=""?tmp[4]:"";var cartoonName=decodeURIComponent(tmp[1]);var link="/Cartoon/detail/id/"+
tmp[0]+"/sid/"+tmp[2]+"/ref/dbyd";var item={"id":tmp[0],"cartoonName":cartoonName,"shortCartoonName":cartoonName.substring(0,10),"link":link,"delType":2,"photoUrl":photoUrl,"viewNo":tmp[2],"nextEpisodeName":""};data.cartoonResult.push(item)}$("#mod-log-his-dh").html(template.render("script-mod-log-his-dh",data));AC.Page.Core.setPanelPagination("#mod-log-his-dh",4)}},deleteReadHistory:function(obj,type,id){if(type==1||type==2){var cookieName="readRecord";if(type==2)cookieName="ac_cartoon_readhistory";
var readRecord=AC.Page.cookie(cookieName);var historyJson=eval(readRecord)||[];var total=historyJson.length;if(total>0){for(var i=0;i<total;i++)if(id==historyJson[i][0]){historyJson.splice(i,1);break}AC.Page.cookie(cookieName,JSON.stringify(historyJson));$(obj).parent("li").remove();if(total==1)if(type==1)$("#mod-log-his-mh").html('<div class="mod-userlog-tips"><h3>\u6682\u65e0\u9605\u8bfb\u8bb0\u5f55</h3><p class="ui-mb40">\u8d76\u7d27\u5f00\u59cb\u7cbe\u5f69\u7684\u6f2b\u753b\u4e4b\u65c5\u5427</p></div>');
else if(type==2)$("#mod-log-his-dh").html('<div class="mod-userlog-tips"><h3>\u6682\u65e0\u9605\u8bfb\u8bb0\u5f55</h3><p class="ui-mb40">\u8d76\u7d27\u5f00\u59cb\u7cbe\u5f69\u7684\u52a8\u753b\u4e4b\u65c5\u5427</p></div>')}}if(type==3||type==4){var url="/ComicView/delReadRecord";if(type==4)url="/Cartoon/delReadHistory";$.post(url,{"cid":id,"tokenKey":AC.Page.Core.token},function(data){if(data.status==1){$(obj).parent("li").remove();if(type==3){var total=$("#mod-log-his-mh .mod-slider-item-wr").length;
if(total==1)$("#mod-log-his-mh").html('<div class="mod-userlog-tips"><h3>\u6682\u65e0\u9605\u8bfb\u8bb0\u5f55</h3><p class="ui-mb40">\u8d76\u7d27\u5f00\u59cb\u7cbe\u5f69\u7684\u6f2b\u753b\u4e4b\u65c5\u5427</p></div>')}else if(type==4){var total=$("#mod-log-his-dh .mod-slider-item-wr").length;if(total==1)$("#mod-log-his-dh").html('<div class="mod-userlog-tips"><h3>\u6682\u65e0\u89c2\u770b\u8bb0\u5f55</h3><p class="ui-mb40">\u8d76\u7d27\u5f00\u59cb\u7cbe\u5f69\u7684\u52a8\u753b\u4e4b\u65c5\u5427</p></div>')}}},
"json")}},loadMessageNotify:function(autoFlag){if(autoFlag){if(AC.Page.Core.hasLogin=="1")$.get("/Ajax/getMessageNotify",{stamp:Math.random()},function(result){if(result.msgList)AC.Page.Core.setMessageCount(result.msgList.length)},"json")}else if(AC.Page.Core.hasLogin=="1")$.get("/Ajax/getMessageNotify",{stamp:Math.random()},function(result){AC.Page.Core.showMessageNotify(result)},"json")},setMessageCount:function(msgCount){if(msgCount>0){$("#mod-top-user .mod-user-msg-num").show();$("#mod-top-user .mod-user-msg-num").text(msgCount>=
99?"99+":msgCount);$("#fix-user .mod-user-msg-num").show();$("#fix-user .mod-user-msg-num").text(msgCount>=99?"99+":msgCount)}else{$("#mod-top-user .mod-user-msg-num").empty();$("#mod-top-user .mod-user-msg-num").hide();$("#fix-user .mod-user-msg-num").empty();$("#fix-user .mod-user-msg-num").hide()}this.msgCount=msgCount},showMessageNotify:function(result){var msgCount=result.msgList.length;this.setMessageCount(msgCount);for(var i=0;i<msgCount;i++){result.msgList[i]["type"]=result.msgList[i].type;
result.msgList[i]["title"]=decodeURIComponent(result.msgList[i].title);result.msgList[i]["id"]=result.msgList[i].id}$("#mod-user-msg").html(template.render("script-mod-user-msg",result));if(msgCount>0)AC.Page.Core.setPanelPagination("#mod-user-msg",2)},clearMessageNotify:function(messageId){$.post("/Ajax/clearMessageNotify",{messageId:messageId,stamp:Math.random()},function(result){var state=result.state;var msgId=result.msgId;if(state==1){$("#li_message_"+msgId).remove();var msgCount=AC.Page.Core.msgCount-
1;var msgNow=$("#ul_message_list li").length;if(msgCount<=0){$("#div_message_detail").hide();$("#p_message_empty").show()}else if(msgNow==0){$("#sp_message_remain").html(msgCount-5);$("#p_message_remain").show()}AC.Page.Core.setMessageCount(msgCount)}},"json")},loadFavoritUpdate:function(autoFlag){if(AC.Page.Core.hasLogin=="1")$.get("/Ajax/getFavoritUpdate",{stamp:Math.random()},function(result){result.hasLogin=AC.Page.Core.hasLogin;AC.Page.Core.showFavoritUpdate(result);AC.Page.Core.setFavoritUpdateCount(result.data.length)},
"json");else{var result={};result["hasLogin"]="0";$("#mod-log-collection").html(template.render("script-mod-log-collection",result));$("#mod-top-log-history").die("click").live("click",function(){AC.Page.Core.loadReadHistory();AC.Page.Core.Timetstamp=Date.parse(new Date)})}},setFavoritUpdateCount:function(updateCount){if(updateCount>0){$("#mod-top-log .mod-user-msg-num").show();$("#mod-top-log .mod-user-msg-num").text(updateCount>=99?"99+":updateCount);$("#fix-log").next().show();$("#fix-log").next().text(updateCount>=
99?"99+":updateCount)}else{$("#mod-top-log .mod-user-msg-num").empty();$("#mod-top-log .mod-user-msg-num").hide();$("#fix-log").next().hide();$("#fix-log").next().empty()}this.updateCount=updateCount},showFavoritUpdate:function(result){var updateCount=result.data.length;this.setFavoritUpdateCount(updateCount);for(var i=0;i<updateCount;i++){var title=decodeURIComponent(result.data[i].title);result.data[i]["title"]=title;result.data[i]["shortTitle"]=title.substring(0,15);result.data[i]["link"]="/ComicView/index/id/"+
result.data[i].id+"/seqno/"+result.data[i].viewSeqNo+"/ref/dbsc";result.data[i]["finish"]=result.data[i].finishState==1?"ui-icon-new":"ui-icon-done";result.data[i]["nextLink"]="/ComicView/index/id/"+result.data[i].id+"/seqno/"+result.data[i].nextSeqNo+"/ref/dbsc";result.data[i]["latedLink"]="/ComicView/index/id/"+result.data[i].id+"/seqno/"+result.data[i].lateSeqNo+"/ref/dbsc";result.data[i]["coverUrl"]="http://ugc.qpic.cn/manhua_cover/0/"+result.data[i].coverUrl+"/100";result.data[i]["comicLink"]=
"/Comic/comicInfo/id/"+result.data[i].id}$("#mod-log-collection").html(template.render("script-mod-log-collection",result));$("#mod-top-log-history").die("click").live("click",function(){AC.Page.Core.loadReadHistory();AC.Page.Core.Timetstamp=Date.parse(new Date)});$(".mod-top-log-animate").die("click").live("click",function(){AC.Page.Core.setPanelPagination("#mod-log-his-dh",4)});AC.Page.Core.setPanelPagination("#mod-log-fav-mh",3)},setPanelPagination:function(viewName,showCount){var logView=function(el){var wrapp=
el,list=wrapp.find(".mod-slider-list"),pageWidth=list.find("li").width(),btnWrapp=wrapp.find("div.mod-slider-btn"),nextBtn=btnWrapp.find("a.mod-slider-btn-next"),prevBtn=btnWrapp.find("a.mod-slider-btn-prev"),delBtn=list.find(".ui-btn-del"),messageCount=list.find("div").length,p=messageCount>0?Math.ceil(messageCount/showCount):1,n=0,isMov=true;var logView={init:function(){this.bindEvent()},bindEvent:function(){var self=this;nextBtn.click(function(){if(!isMov)return false;n+=1;if(n>=p){n=p-1;return false}self.setAnimate()});
prevBtn.click(function(){if(!isMov)return false;n-=1;if(n<0){n=0;return false}self.setAnimate()});delBtn.click(function(){var work=$(this).parents(".mod-slider-item-wr"),parent=work.parent(),index=work.attr("index");work.fadeOut(function(){var ts=$(this).siblings().size(),ps=parent.siblings().size();if(ts==0){parent.remove();n-=1;self.setAnimate(n)}if(ts==0&&ps==0){list.parent().prev().show();return false}work.remove();var next=parent.nextAll(),nextSize=next.size();parent.append(parent.next().find("div:first"));
next.each(function(i){var n=$(this).next();$(this).append(n.find("div:first"));$.trim($(this).html())===""&&$(this).remove()});p=list.find("li").size();if(p<=1)btnWrapp.remove()})})},setAnimate:function(){var position=pageWidth*n;if(isMov){isMov=false;list.stop().animate({"margin-left":-position},500,function(){isMov=true})}}};logView.init()};if(viewName=="#mod-user-msg"){logView($("#mod-user-msg"));AC.Page.Core.dropBox({handle:$(".mod-top-user-msg"),panel:$("#user-info"),offsetLeft:-241,offsetTop:15})}else if(viewName==
""){if(AC.Page.Core.hasLogin=="1")AC.Page.Core.dropBox({handle:$(".mod-top-user-msg"),panel:$("#user-info"),offsetLeft:-241,offsetTop:15});AC.Page.Core.dropBox({handle:$(".mod-top-user-log"),panel:$("#log-info"),offsetLeft:-276,offsetTop:15})}else{if(viewName=="#mod-log-fav-mh")logView($("#mod-log-fav-mh"));else if(viewName=="#mod-log-his-dh")logView($("#mod-log-his-dh"));else if(viewName=="#mod-log-his-mh")logView($("#mod-log-his-mh"));AC.Page.Core.dropBox({handle:$(".mod-top-user-log"),panel:$("#log-info"),
offsetLeft:-276,offsetTop:15})}},dropBox:function(opts){var deley=opts.deley||100,handle=opts.handle||null,panel=opts.panel||null,offsetLeft=parseInt(opts.offsetLeft)||0,offsetTop=parseInt(opts.offsetTop)||0,positionLeft=0,positionTop=0;var dropBox={timer:null,isActive:true,view:function(){if(handle[0]&&panel[0])this.bindEvent()},bindEvent:function(){var self=this;$(window).resize(function(){self.getPosition()});handle.hover(function(){self.getPosition();self.dropShow();self.timer&&clearTimeout(self.timer)},
function(){self.timer=setTimeout(function(){self.dropHide()},deley)});panel.hover(function(){self.timer&&clearTimeout(self.timer)},function(){setTimeout(function(){self.dropHide()},100)})},getPosition:function(){positionLeft=parseInt(handle.offset().left+offsetLeft);positionTop=parseInt(handle.height()+handle.offset().top+offsetTop);opts.fixed&&(positionTop=parseInt($(document).scrollTop()+handle.height()+offsetTop))},dropShow:function(){var self=this;if(!this.isActive)return;panel.css({"position":"absolute",
"z-index":60,"left":positionLeft,"top":positionTop}).show();this.isActive=false},dropHide:function(){panel.hide();this.isActive=true}};dropBox.view()},sideTool:function(){var sideWr=$("#mod-side-tool"),scrollTopElement=$("#scroll-top"),sideTimer;if(sideWr[0]){$(window).bind("scroll",function(){var scrollTopVal=$(this).scrollTop();if(sideTimer)clearTimeout(sideTimer);sideTimer=setTimeout(function(){scrollTopVal>400?sideWr.fadeIn():sideWr.fadeOut()},200)});scrollTopElement.click(function(){$("html, body").animate({scrollTop:0},
100)})}}};AC.namespace("AC.UI.Tabs");
AC.UI.Tabs={view:function(options){var defaults={eventType:"mouseover",wrap:null,handle:null,panel:null,activeClass:"active",delay:100,callback:null},opts=$.extend({},defaults,options),timer,change=function(handle,panel,index){handle.siblings().removeClass(opts.activeClass);handle.addClass(opts.activeClass);panel.eq(index).show().siblings().hide();opts.callback&&opts.callback(handle)};if(opts.wrap){opts.handle=opts.wrap.find(".tabs-handle").children();opts.panel=opts.wrap.find(".tabs-panel").children()}if(opts.eventType==
"hover")opts.eventType="mouseover";opts.handle.bind(opts.eventType,function(){var $this=$(this),idx=$this.index();if($this.hasClass(opts.activeClass))return false;timer&&clearTimeout(timer);if(opts.delay)timer=setTimeout(function(){change($this,opts.panel,idx)},opts.delay);else change($this,opts.panel,idx)});opts.handle.eq(0).addClass(opts.activeClass);opts.panel.eq(0).show().siblings().hide()}};AC.namespace("AC.UI.PopUp");
AC.UI.PopUp={timer:null,closeHolder:".ui-popup-btn-close, .ui-popup-closer",createBasicSkin:function(settings){var title=settings.title||"",content=settings.content||"",foot=settings.foot||"",_class=settings._class||"",basicHtml="";basicHtml+='<div class="ui-popup-wr '+_class+'"><div class="ui-popup-content-wr">';if(typeof title==="string"&&$.trim(title)!=="")basicHtml+='<div class="ui-popup-head"><h3 class="ui-popup-title">'+title+"</h3></div>";basicHtml+='<div class="ui-popup-content">'+content+
"</div>";if(typeof foot==="string"&&$.trim(foot)!=="")basicHtml+='<div class="ui-popup-foot-wr">'+foot+"</div>";basicHtml+='</div><sub class="ui-popup-closer">\u5173\u95ed</sub></div>';return basicHtml},closePanel:function(){var self=this;return $(self.closeHolder).on("click",function(){self.hide()})},elementReady:function(element,contentSettings){var self=this,isFirst=true,elemContent;if(element.find(".ui-popup-wr")[0])isFirst=false;if(isFirst){$("#_PopupMsg_").css({"border":"none","padding":"0px"});
elemContent=self.createBasicSkin(contentSettings);element.children().remove();$(elemContent).prependTo(element)}},showElement:function(elementId,title){var element=$("#"+elementId);showDialog.show({id:elementId,bgcolor:"#000",opacity:30,deleyPop:true});this.elementReady(element,{title:title||"",content:element.html()});this.action();this.closePanel()},showMsg:function(msgContext,msgType){var self=this,settings={content:'<div class="ui-popup-msg clearfx"><i></i><p class="ui-popup-msg-text">'+msgContext+
"</p></div>"},time=2E3,msgContent;var statusClass=msgType=="1"?"succeed":msgType=="2"?"failed":"warning";settings._class=statusClass;msgContent=this.createBasicSkin(settings);showDialog.show({sMsg:msgContent,bgcolor:"#000",opacity:30,sStyle:"border:none;border-radius:3px;padding:0;",onCloseCallback:function(){self.timer&&clearTimeout(self.timer)}});self.timeout(time);this.action();this.closePanel()},show:function(options){var self=this,opts,contentHtml,popCallbak;opts=$.extend({elementId:null,frameSrc:null,
bgcolor:"#000",opacity:30,width:350,height:150,hideTime:0,title:"",foot:"",content:"popup content",popClass:"",delayPop:false,onPopupCallback:null,onCloseCallback:null,okCallback:null,callback:null},options),contentSettings={title:opts.title,content:opts.content,foot:opts.foot,_class:opts.popClass};contentHtml=this.createBasicSkin(contentSettings);if(opts.frameSrc||opts.elementId)opts.delayPop=true;if(opts.elementId)contentHtml=null;showDialog.show({id:opts.elementId,src:opts.frameSrc,bgcolor:opts.bgcolor,
opacity:opts.opacity,iWidth:opts.width,iHeight:opts.height,sMsg:contentHtml,delayPop:opts.delayPop,sStyle:"border:none;border-radius:3px;padding:0;",onPopupCallback:function(){opts.onPopupCallback&&opts.onPopupCallback()},onCloseCallback:function(){self.timer&&clearTimeout(self.timer);if(opts.callback)opts.callback=null;opts.onCloseCallback&&opts.onCloseCallback()}});if(opts.elementId){var element=$("#"+opts.elementId);contentSettings["content"]=element.html();self.elementReady(element,contentSettings)}if(opts.frameSrc&&
opts.delayPop)$("#_PopupIframe_").appendTo($(".ui-popup-content-wr"));if(opts.hideTime)self.timeout(opts.hideTime);$(".ui-popup-callback").live("click",function(){if(opts.callback)opts.callback()});this.closePanel();this.action()},timeout:function(time){var self=this;self.timer=setTimeout(function(){self.hide()},time)},action:function(){return showDialog.popup()},hide:function(param){var bool=param==false?{cancleCallback:true}:"";showDialog.hide(bool)},savet:function(){var self=this;self.hide();setTimeout(function(){location.reload()},
1E3)}};AC.namespace("AC.UI.Slider");
AC.UI.Slider={show:function(list,opts){var list=$(list),opts=$.extend({mode:"fade",speed:600,auto:true,autoDelay:2E3,loop:true,captions:false,pager:true,arrow:true,lazy:false,randomStart:false},opts);if(list.children().size()>1){var Slider=list.bxSlider({mode:opts.mode,infiniteLoop:opts.loop,auto:opts.auto,autoDelay:opts.autoDelay,captions:opts.captions,speed:opts.speed,pager:true,randomStart:opts.randomStart,onSlideBefore:function(el,o,n){var clone=el.siblings(".bx-clone");if(opts.lazy)if(opts.mode==
"fade")AC.Page.loadImage(el.siblings(),true);else if(n===Slider.getSlideCount()-1&&clone[0])AC.Page.loadImage(clone,true)}});var parant=list.parents(".bx-wrapper"),pager=parant.find(".bx-pager"),arrow=parant.find(".bx-controls-direction");if(!opts.pager)pager.css("display","none");if(!opts.arrow)arrow.css("display","none");parant.addClass("mod-slider").css("position","relative");parant.hover(function(){Slider.stopAuto()},function(){Slider.startAuto()})}}};
